/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import lombok.RequiredArgsConstructor;
import org.apache.olingo.client.api.ODataClient;
import org.apache.olingo.client.api.communication.request.retrieve.RetrieveRequestFactory;

@RequiredArgsConstructor
public class Library {

    private final ODataClient oDataClient;

    public boolean someLibraryMethod() {
        RetrieveRequestFactory factory = this.oDataClient.getRetrieveRequestFactory();
        if (factory == null) {
            throw new MyException();
        }
        return true;
    }
}
